#!/usr/local/bin/ruby -w
# Copyright (c) 2008, Marcin Simonides
# Copyright (c) 2009, Marius Nuennerich
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

require 'zsnap'

config_yaml = File.open(Zsnap::CONFIG_FILE_NAME).read(Zsnap::CONFIG_SIZE_MAX)
die "reading config file" unless config_yaml
config = Zsnap::Config.new(YAML::load(config_yaml))

now_minutes = Time.now.to_i / 60

# A simple way of avoiding interaction with zpool scrubbing
busy_pools = config.busy_pools

config.filesystems.each do |fs|
  unless busy_pools.include? fs.pool
    fs.create_snapshot(now_minutes, config.snapshot_prefix)
    fs.remove_snapshots(now_minutes, config.snapshot_prefix)
  end
end
